### PR TITLE
fix discover on Android

### PR DESCRIPTION
**Pull request by EduardoRFS**
Android doesn't require `-lrt` as it's built into the libc bionic.

With Mirage can be compiled for Android using https://github.com/EduardoRFS/reason-mobile

### CODE REVIEW

**Comment by dinosaure** [comment]
Interesting, can you add something in Travis CI to ensure to keep the portability on Android?

**Comment by EduardoRFS** [comment]
@dinosaure would you guys accept a github actions workflow instead? I have no experience with travis but I already have a github actions capable of testing this

**Comment by hannesm** [comment]
@EduardoRFS sure, we take any CI that works ;)

**Comment by EduardoRFS** [comment]
CI Added, here is the results on my repository

> https://github.com/EduardoRFS/mirage-clock/runs/1328824074?check_suite_focus=true

**Comment by dinosaure** [comment]
Thanks, did you want a release as soon as we can @EduardoRFS ?

**Comment by EduardoRFS** [comment]
@dinosaure no pressure, I have this patch automatically applied for 3.0.1

**Pull request merged**
