### PR TITLE
Port to jbuilder

### PR DESCRIPTION
**Pull request by avsm**
This needs careful review and testing to make sure that the new configurator based cflags are correct

### CODE REVIEW

**Comment by hannesm** [comment]
could you please elaborate on whether there was any testing done with xen and/or solo5 unikernels using this PR?  if not, please compile and test some unikernels and report back.  thx.

**Comment by djs55** [comment]
Do we have any example unikernel configurations in `opam-repository`? Now that the `mirage` tool doesn't need to run `opam` as part of the build, and now that `mirage configure` generates a `name.opam` file (all very nice improvements IMHO), I think we should be able to publish some -- is that correct? If we had a few example unikernels in the repo, perhaps we could more easily test they build as part of the CI revdeps steps?

**Comment by hannesm** [comment]
On 05/06/2017 13:24, Dave Scott wrote:
> Do we have any example unikernel configurations in `opam-repository`? Now that the `mirage` tool doesn't need to run `opam` as part of the build, and now that `mirage configure` generates a `name.opam` file (all very nice improvements IMHO), I think we should be able to publish some -- is that correct? If we had a few example unikernels in the repo, perhaps we could more easily test they build as part of the CI revdeps steps?

this is viable.  I wouldn't convolute the main opam-repository with
this, but rather a mirage repository with this... you can even have some
post-commit hook for unikernel repos, which run mirage configure
-t {} and update the opam files in the that repo (the generated
name.opam should consists of unikernel name and target.. it may even be
worth to include some build instructions in the generated opam files).

**Comment by avsm** [comment]
> could you please elaborate on whether there was any testing done with xen and/or solo5 unikernels using this PR?

solo5 yeah -- I'm provisioning a freebsd box to test out the virtio backends atm.

**Comment by avsm** [comment]
yes a separate remote with all the configuration steps in a new repo would be great. will take a look at this.

**Comment by avsm** [comment]
Woohoo! FreeBSD Virtio DNS server succeeds fine with this PR in the pin list. Just a minor issue https://github.com/Solo5/solo5/pull/197 found

**Comment by avsm** [comment]
And the Linux Xen and UKVM examples in static_tls build and work as well with this pin. The configuration here is now simpler as well due to using Configurator (rather than the ocamlbuild tags), but something may have regressed despite all these checks due to the different `cclib` options.  I'm going to merge this so it's in master and let it settle for a few days while I inspect more command lines to be sure...

**Pull request merged**
